{% set name = "energymon" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/energymon-{{ version }}.tar.gz
  sha256: b5fbf1369ee01f60cfef0f1488fa61093ee3751f6facb7b0ef087f46ce931820

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=42
  run:
    - python >=3.6

test:
  imports:
    - energymon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/energymon/energymon-py
  summary: Python bindings to native energymon libraries
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
  description: |
    This project provides Python bindings to energymon libraries.
  doc_url: https://energymon-py.readthedocs.io/
  dev_url: https://github.com/energymon/energymon-py

extra:
  recipe-maintainers:
    - connorimes
